### ISSUE TITLE
Generalized Error while createToken - "Card details not complete" with CardField

### ISSUE THREAD

**Issue by hafizusman2** [stripe/stripe-react-native#1594]
I tried multiple options as mentioned
No issue found in my code
I tried by using StripeProvider
also tried by using initStripe method
I am consistently facing the following error:

`{"error": {"code": "Failed", "declineCode": null, "localizedMessage": "Card details not complete", "message": "Card details not complete", "stripeErrorCode": null, "type": null}}`
blocked
@charliecruzan-stripe @gabriellend

here is my code
```
import {Box, KeyboardAvoidingView, Stack, Text, useTheme, View} from 'native-base';
import {CardField, initStripe, StripeProvider, useStripe} from '@stripe/stripe-react-native';
import {Config} from 'react-native-config';
import React, {useContext, useEffect, useState} from 'react';
import LoadingScreen from 'components/LoadingScreen';
import {AuthContext} from 'context/authContext';
import GoToNext from 'screens/GoalCreating/components/GoToNext';
import {TOAST_TYPE, ToastContext} from 'context/toastContext';
import {CREATED_ROUTES} from 'screens/GoalCreating/constants';
import {useNavigation} from '@react-navigation/native';
import {
  AmericanExpressIcon,
  DinnerClubIcon,
  DiscoverCardIcon,
  MastercardIcon,
  UnionPayIcon,
  VisaCardIcon
} from 'assets/icons/cards';
import {Platform} from 'react-native';
const {STRIPE_PUBLISHABLE_KEY} = Config;

console.log('STRIPE_PUBLISHABLE_KEY', STRIPE_PUBLISHABLE_KEY);

const PaymentToken = () => {
  const {createToken} = useStripe();
  const {me} = useContext(AuthContext);
  const {colors} = useTheme();
  const {addToast} = useContext(ToastContext);
  const {navigate} = useNavigation();

  const [loading, setLoading] = useState(false);
  const [loadingPay, setLoadingPay] = useState(false);
  const [paymentMethodData, setPaymentMethodData] = useState();
  const [cardData, setCardData] = useState();

  const initializeStripe = async () => {
    setLoading(true);
    try {
      await initStripe({
        publishableKey: 'pk_test_U9omQHnm44eocSCqocC4JUOp00tnnig3IV'
      });
      console.log('stripe initialized');
    } catch (e) {
      console.log('error in init stripe', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    initializeStripe();
  }, []);

  const handlePayPress = async () => {
    setLoadingPay(true);
    try {
      if (!cardData.complete) {
        console.log('card details not complete in creating stripe token', cardData);
        addToast({type: TOAST_TYPE.ERROR, text: 'Please fill the card details'});
        return;
      }

      await initializeStripe();

      console.log('cardData', cardData);
      const resToken = await createToken({
        type: 'Card'
      });
      if (resToken.error) {
        console.log('error in creating stripe token', resToken);
        addToast({type: TOAST_TYPE.ERROR, text: resToken.error.message});
        return;
      }

      addToast({type: TOAST_TYPE.SUCCESS, text: 'Card was added successfully'});
    } catch (e) {
      console.log('error in creating stripe token', e);
    } finally {
      setLoadingPay(false);
    }
  };

  const fetchCardDetails = cardDetail => {
    if (cardDetail?.complete) {
      return setCardData(cardDetail);
    }
    // setCardData(null);
  };

  const behavior = Platform.OS === 'ios' ? 'padding' : 'height';

  if (loading) return <LoadingScreen />;
  return (
    <View flex={1} px={4}>
      <KeyboardAvoidingView
        keyboardVerticalOffset={120}
        behavior={behavior}
        style={{
          flex: 1
        }}
      >
        <View flex={1}>
          <Text fontWeight={'600'}>Add payment method</Text>
          <Stack direction={'row'} justifyContent={'space-between'} mt={5}>
            <MastercardIcon />
            <VisaCardIcon />
            <UnionPayIcon />
            <AmericanExpressIcon />
            <DinnerClubIcon />
            <DiscoverCardIcon />
          </Stack>
          <StripeProvider publishableKey={STRIPE_PUBLISHABLE_KEY}>
            <CardField
              postalCodeEnabled={false}
              placeholders={{
                number: '4242 4242 4242 4242'
              }}
              cardStyle={{
                backgroundColor: '#FFFFFF',
                textColor: '#000000',
                placeholderColor: colors.secondary[200]
              }}
              style={{
                width: '100%',
                height: 50,
                marginVertical: 30
              }}
              onCardChange={cardDetails => {
                fetchCardDetails(cardDetails);
              }}
            />
          </StripeProvider>
          <View style={{flexGrow: 1}} />

          <Box mb={6}>
            <GoToNext handleSubmit={handlePayPress} isLoading={loadingPay} title={'save'} disabled={!cardData} />
          </Box>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
};

export default PaymentToken;

```

**Comment by charliecruzan-stripe** [comment]
I believe this is an old bug so can you try updating your SDK version?

**Comment by hafizusman2** [comment]
its updated
compileSdkVersion: 33
    "react-native": "0.70.8",
    "@stripe/stripe-react-native": "^0.28.0",
@charliecruzan-stripe

**Comment by charliecruzan-stripe** [comment]
Yeah this should be fixed in the most recent version

**Comment by hafizusman2** [comment]
You saying, that I have to update version?

**Comment by jaynewstrom-stripe** [comment]
Please reopen if this isn't fixed in the latest version.

**Comment by macro6461** [comment]
Anybody else still having this issue? I am on RN and @stripe/stripe-react-native v.^0.59.1. I am trying to use CardForm and createToken. It's my understanding that country/postal code and card number are all stored securely in the stripe provider so I don't need to see it in the completed card details. I have checked my connected stripe account and publishable key and they are both valid
