### ISSUE TITLE
[Bug] [Android] CardField onCardChange not triggering in React Native Stripe

### ISSUE THREAD

**Issue by RohanRajGautam** [stripe/stripe-react-native#1812]
**Describe the bug**
The CardField component's onCardChange callback is not triggering when entering card details. No values are being received in the callback function, making it impossible to capture and validate card information.

**To Reproduce**
1. Initialize Stripe in your React Native app
2. Implement CardField component with onCardChange handler
3. Run the app and navigate to the credit card input screen
4. Try entering card details in the field
5. Check console logs - no output is shown
6. Check card state - remains null

Code example:

```
<CardField
postalCodeEnabled={false}
placeholders={{
number: '1234 1234 1234 1234',
}}
cardStyle={{
backgroundColor: '#FFFFFF',
textColor: '#000000',
}}
style={{
height: 50,
width: '100%',
}}
onCardChange={(cardDetails) => {
console.log('Card Details:', cardDetails);
setCard(cardDetails.complete ? cardDetails : null);
}}
/>
```

**Screenshot**

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/4a5cb0a5-743d-460c-9e3b-58edd9023814" />

**Expected behavior**
- onCardChange callback should fire whenever user enters or modifies card details
- Callback should receive CardFieldInput.Details object containing card information
- Console should show logged card details
- Card state should update when details are complete

**Smartphone (please complete the following information):**
- Device: Android
- React Native Version: 0.76.1
- @stripe/stripe-react-native Version: [^0.39.0]

**Additional context**
- Component renders correctly and is visible
- No error messages in console
- Other Stripe components working as expected
- Stripe initialization is successful
- Issue occurs on Android only 

**Possible Workarounds Needed**
Looking for either:
1. Correct implementation of CardField with working onCardChange
2. Alternative method to capture card details
3. Any known workarounds for this issue

**Comment by glopez-askit** [comment]
Same issue, the new architecture is being a huge problem for this library.

**Comment by kaushil111** [comment]
Same!

**Comment by Noesersi** [comment]
Same, is anyone trying to implement payment element instead?

**Comment by kaushil111** [comment]
Here is a patch that works with fabric enabled app on Android:

[@stripe-stripe-react-native-npm-0.41.0-7a76d4dacd.patch](https://github.com/user-attachments/files/18552615/%40stripe-stripe-react-native-npm-0.41.0-7a76d4dacd.patch)

It also includes the patch for https://github.com/stripe/stripe-react-native/issues/1732 with slight modifications. Here is the reference:
https://github.com/stripe/stripe-react-native/issues/1732#issuecomment-2594110710

**Comment by mostafijur-rahman299** [comment]
Same issue

**Comment by SharkZekrom** [comment]
same issue

**Comment by obirikan** [comment]
same issue

**Comment by rajbhakta05** [comment]
Same Issue

**Comment by obirikan** [comment]
i had to use the webview version on my expo react native app cause the app is in production and android users cannot make payment

**Comment by sergio-cravas** [comment]
Is there any update on this? I'm facing the same problem

**Comment by joyceqin-stripe** [comment]
Hi all, thank you all for your patience. I'm sorry it's taken us way too long to support the new architecture. We have begun our work to start migrating to the new architecture over the past couple of weeks and hope to complete it over the next 4-6 weeks. If anything changes, you can expect to see an update, but I'm optimistic we should be able to complete it by then.

This particular issue should be fixed in the latest version 0.40.0.

I apologize again for the delay. Please keep the feedback coming as well; we will do a better job at communicating with you all in GitHub issues going forward. I will close this issue for now, but please re-open if you continue to experience this issue after updating to the latest version.

**Comment by rajbhakta05** [comment]
I Tried 0.40.0 also latest one 0.43.0, but still facing the same issue, no call back from onCardChange

**Comment by mostafijur-rahman299** [comment]
> Is there any update on this? I'm facing the same problem

It might have been resolved in the latest update. I faced the same issue earlier—after upgrading the package, it works fine on Android. However, for iOS, you need to run an additional command during pod install.

**Comment by hamza-id** [comment]
I implemented a workaround by making direct Stripe API calls.

**Comment by Youssefkadri05** [comment]
i fixet it with     
"@stripe/stripe-react-native": "0.37.2",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "expo": "~51.0.36",

**Comment by obirikan** [comment]
A simple workaround is to use Stripe Checkout inside a WebView. This way, you can handle payments without ejecting your Expo app.
It’s a good temporary solution until the issue is resolved 

I was using it in production so I had to change it for users to make payment
