### ISSUE TITLE
Is the lib ready for production?

### ISSUE THREAD

**Issue by rdewolff** [stripe/stripe-react-native#435]
Hey all

Great seeing this new lib! We have been using `tipsi-stripe` for a few years now and are looking into migrating to this new lib. Before going really deeper, I tried to test some features as described in https://stripe.com/docs/payments/accept-a-payment?platform=react-native. Then I started to face some issues like the one described in #315. 

During my initial tests, I tried and failed using some methods, like `presentPaumentSheet()`. But I did not get any error message nor reaction from the lib. For example if you haven't called `initPaymentSheet()` before. This is rather concerning. 

So here is the main million dollars question, is `stripe-react-native` ready for production? What do you think?

Thanks for your feedback and opinions on this.

**Comment by aliriaz-stripe** [comment]
@rdewolff hello! The library is ready for production, yes. 

I appreciate your feedback around the places lacking validation or error messages in some integration paths (and the other issue you linked which should be fixed now). PaymentSheet was a recent addition to this library (and also fairly new in the iOS/Android mobile SDKs) so there will be things that will be improved with time and fixed.

**Comment by fdelacruzsoto** [comment]
I'd say it is not ready, I tried to implement the setup intent method and it didn't work, I opened two issues here asking for help and giving details, the first issue was closed with a "check the documentation" comment and the second issue is still open but no one is looking at it.

I gave details on how to reproduce the issue and got ignored, I submitted a PR with a fix that worked for us and they rejected it.

I see a lot of people having the same issues as I do, and some additional issues, but looks like no one from stripe cares about them.

**Comment by thorsten-stripe** [comment]
@fdelacruzsoto I'm sorry that this has been your experience, unfortunately the cause of your specific issue was not obvious and it took quite some time until we were able to reproduce it. 

We definitely appreciate that you've taken the time to provide a PR with a potential solution, unfortunately we weren't able to merge it since it would have affected other payment scenarios.

We are sorry it took so long and we very much hope that this won't happen again.

@rdewolff the library is in public beta and ready for production. Of course please do open issues if you run into specific problems or have actionable feedback, we very much appreciate it. I'll leave it up to you whether you want to close this issue or keep it open for more opinions from the community.

**Comment by babyrusa** [comment]
I agree with @fdelacruzsoto

**Comment by tobiastornros** [comment]
On that note, Setup Intents is still broken and examples in this repo regarding setup intent and on https://stripe.com/docs/payments/save-and-reuse?platform=react-native does not work.

**Comment by tobiastornros** [comment]
Clarification from stripe support regarding Setup Intents. React native SDK grabs the card information under the hood and apply it to the confirmSetupIntent function and that is why we cant manually apply it to the function.

**Comment by charliecruzan-stripe** [comment]
I'm curious if anyone has new thoughts on this now? Would love to hear feedback on the most recent versions of the library. We're gearing up for our V1 release soon 😄

**Comment by adrien-may** [comment]
Things are starting to flat out (especially with the latest releases). We tried almost all features (card field, paymentSheet, setupIntent, confirmIntent, types...), we're quite up to date with react-native and platform versions so we don't have much issues with legacy and were able to follow along. I'd say this is not far to be robust enough for a v1. We do use it in production and most of our issues have been addressed now.

Documentation on subscriptions and paymentSheet is still a bit unclear to me (see my issue #964 )

Also this is not clearly documented on how to use subscription to have paymentIntent and/or setupIntent in the backend with PaymentSheet. A one off purchase payment example is given (subscriptions are more or less discouraged in favor of in-app purchases)

Something like this for the backend:

```typescript
 const subscription = await stripe.subscriptions.create({
      customer: customerId,
      items: [{ plan: planId }],
      // To allow subscription to be created without paymentMethod in the first place
      payment_behavior: 'default_incomplete',
      // payment_intent if a payment is required
      // pending_setup_intent if trial period or with a coupon that makes the first payment to be 0$
      expand: ['latest_invoice.payment_intent', 'pending_setup_intent'],
      promotion_code: promotionCode,
      trial_from_plan: true,
    });
```

could save a lot of fuzzy search on the stripe docs. Most tutorials are incomplete on the matter and error prone. A complete example with subscriptions + payment sheet could be a real plus.

**Comment by charliecruzan-stripe** [comment]
I agree that some documentation on the existing story between PaymentSheet and subscriptions is necessary, will keep that in mind :) @adrien-may what do you mean that things are starting to flat out? I'm unsure if that's a positive sentiment or a negative one 😅  If it's negative, lmk what else has been difficult for you and we can try to make things better!

**Comment by adrien-may** [comment]
Oh I'm sorry, that was a positive feedback, I did not even think about taking it the bad way.  What I meant : issues are starting to decline on our point of view, it's getting more and more stable for us. The latest fixes were the most important for us. More work is underway to customize elements and initial "bugs" have been resolved now.

**Comment by charliecruzan-stripe** [comment]
Thanks so much for that! We want the React Native story at stripe to just get better and better 🔥

**Comment by mircovippinn** [comment]
@charliecruzan-stripe Do I need to do any additional configuration or permission to enable real payments with Google Pay and Apple Pay in production? Or simply following all the steps in the documentation
of PaymentSheet would already be enabled?

**Comment by charliecruzan-stripe** [comment]
You're good to go as long as you've followed all the steps [here for Apple Pay](https://stripe.com/docs/apple-pay?platform=react-native) and [here for Google Pay](https://stripe.com/docs/google-pay)

**Comment by talaikis** [comment]
Not really, because documentation is a mess.

**Comment by charliecruzan-stripe** [comment]
Thanks, that's really good to know! Improving the embedded documentation is on the roadmap, and will make it so that there's less need to comb through integration guides to find what you're looking for.
