### ISSUE TITLE
[0.12.0] Opening > Closing > Re-opening the payment sheet makes the app crash on android

### ISSUE THREAD

**Issue by xseignard** [stripe/stripe-react-native#999]
**Describe the bug**
Opening > Closing > Re-opening the payment sheet makes the app crash on android only (happening in debug and prod builds)

**To Reproduce**
1. Open a payment sheet
2. Dismiss it with the close cross icon
3. Try to re-open it
4. The app crashes

**Expected behavior**
The payment sheet should re-open

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Browser N/A (react-native)
 - Version `"@stripe/stripe-react-native": "0.12.0"`

**Additional context**
Please find the stack trace below:
```java
java.lang.IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract com.stripe.android.paymentsheet.PaymentSheetContract@d092c11 and input Args(clientSecret=PaymentIntentClientSecret(value=XXXX), config=Configuration(merchantDisplayName=Alan Mind, customer=CustomerConfiguration(id=XXXX, ephemeralKeySecret=XXXX), googlePay=GooglePayConfiguration(environment=Production, countryCode=FR, currencyCode=), primaryButtonColor=null, defaultBillingDetails=null, allowsDelayedPaymentMethods=false, appearance=Appearance(colorsLight=Colors(primary=-7507457, surface=-1, component=-1, componentBorder=-2366732, componentDivider=-2366732, onComponent=-4932397, onSurface=-14145488, subtitle=-6446150, placeholderText=-4932397, appBarIcon=-4932397, error=-36795), colorsDark=Colors(primary=-7507457, surface=-1, component=-1, componentBorder=-2366732, componentDivider=-2366732, onComponent=-4932397, onSurface=-14145488, subtitle=-6446150, placeholderText=-4932397, appBarIcon=-4932397, error=-36795), shapes=Shapes(cornerRadiusDp=16.0, borderStrokeWidthDp=1.0), typography=Typography(sizeScaleFactor=1.0, fontResId=2131296256), primaryButton=PrimaryButton(colorsLight=PrimaryButtonColors(background=null, onBackground=-1, border=0), colorsDark=PrimaryButtonColors(background=null, onBackground=-1, border=0), shape=PrimaryButtonShape(cornerRadiusDp=16.0, borderStrokeWidthDp=null), typography=PrimaryButtonTypography(fontResId=null, fontSizeSp=null)))), statusBarColor=null, injectorKey=PaymentSheetLauncher2). You must ensure the ActivityResultLauncher is registered before calling launch().
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
    at androidx.fragment.app.Fragment$9.launch(Fragment.java:3507)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at com.stripe.android.paymentsheet.DefaultPaymentSheetLauncher.present(DefaultPaymentSheetLauncher.kt:102)
    at com.stripe.android.paymentsheet.DefaultPaymentSheetLauncher.presentWithPaymentIntent(DefaultPaymentSheetLauncher.kt:82)
    at com.stripe.android.paymentsheet.PaymentSheet.presentWithPaymentIntent(PaymentSheet.kt:65)
    at com.reactnativestripesdk.PaymentSheetFragment.present(PaymentSheetFragment.kt:151)
    at com.reactnativestripesdk.StripeSdkModule.presentPaymentSheet(StripeSdkModule.kt:135)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:920)
```
    
And how the PaymentSheet is initialized:
```ts
const { error } = await initPaymentSheet({
  ...intent, // intent is PaymentSheet.SetupParams
  allowsDelayedPaymentMethods: false,
  merchantDisplayName: 'XXXXX',
  merchantCountryCode: 'FR',
  // google pay conf
  googlePay: true,
  testEnv: __DEV__,
  // apple pay conf
  applePay: true,
  returnURL: `${config.DEEP_LINK_URL_SCHEME}${config.STRIPE_3DS_CALLBACK}`,
  appearance: {
    font: {
      family:
        Platform.OS === 'android' ? FONT_NAME_FOR_ANDROID_PAYMENT_SHEET : fontFamily.regular,
    },
    colors: {
      primary: colors.purple,
      background: colors.white,
      componentBackground: colors.white,
      componentBorder: colors.grey200,
      componentDivider: colors.grey200,
      primaryText: colors.grey900,
      secondaryText: colors.grey500,
      componentText: colors.grey400,
      placeholderText: colors.grey400,
      icon: colors.grey400,
      error: colors.negative,
    },
    shapes: {
      borderRadius: sizes.borderRadius.size16.borderRadius,
    },
    primaryButton: {
      shapes: {
        borderRadius: sizes.borderRadius.size16.borderRadius,
      },
    },
  },
});
```

**Comment by Demonbruster** [comment]
I'm facing this issue right now, Any quick solution please

**Comment by charliecruzan-stripe** [comment]
Hi! thanks for this bug report, the stack trace was really helpful!

We're working on a fix, but for a workaround, you can comment out [this line](https://github.com/stripe/stripe-react-native/blob/master/android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt#L103) (or use something like `patch-package` to comment it out automatically after your `yarn install` step).

**Comment by LivanDiaz** [comment]
Hello @charliecruzan-stripe  I hope you are doing well. I made the changes in the files
-android/src/main/java/com/reactnativestripesdk/PaymentSheetFragment.kt
-android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt

as in the solution (#1014 on Jun 30, 2022) but I still have the same error when I open the (initPaymentSheet) cancel it and open it again in Android),
-Is there any additional step to those?
-Is there something to do after changing those files so that the changes are reflected?

I would really appreciate it if you could help me with that.

**Comment by LivanDiaz** [comment]
@charliecruzan-stripe 
![2023-01-06_13h52_35](https://user-images.githubusercontent.com/62274034/211080125-f2178fc4-3cb5-49f6-8b3a-37693054b83b.png)
![2023-01-06_13h54_59](https://user-images.githubusercontent.com/62274034/211080132-0c7d094a-0715-4cb4-9a11-3b00b910f9f1.png)

**Comment by charliecruzan-stripe** [comment]
@LivanDiaz is there something blocking you from upgrading to version 0.14.0 to get the fix?

**Comment by LivanDiaz** [comment]
What do you recommend I can do?

![2023-01-06_18h22_24](https://user-images.githubusercontent.com/62274034/211115997-b827f8ed-afde-415b-9ca0-ed6ac7c256f4.png)

**Comment by LivanDiaz** [comment]
> @LivanDiaz is there something blocking you from upgrading to version 0.14.0 to get the fix?

fixed @charliecruzan-stripe  , update the version of expo and other dependencies and working perfectly, I appreciate your help.

**Comment by abdullahIsa** [comment]
I am currently having this issue whenever I close and tried to reopen it throws the error and app freezez .

"react-native": "0.70.6",
@stripe/stripe-react-native": "^0.23.1"

**Comment by LivanDiaz** [comment]
@abdullahIsa Hi, Im using actually the version ("@stripe/stripe-react-native": "0.19.0",) and ("react-native": "0.70.5",) 
 and it is working correctly in both Systems (Android y IOS), downgrade your version of (stripe) and test it again.

**Comment by abdullahIsa** [comment]
> @abdullahIsa Hi, Im using actually the version ("@stripe/stripe-react-native": "0.19.0",) and ("react-native": "0.70.5",) and it is working correctly in both Systems (Android y IOS), downgrade your version of (stripe) and test it again.

Hello, I tried that seems to throw error still, I noticed it happens after I have done a payment, also not sure if you noticed if you are using presentPaymentSheet function if user closes it while they have a card saved wont throw error, an issue that was open about it [https://github.com/stripe/stripe-react-native/issues/723](https://github.com/stripe/stripe-react-native/issues/723)

for the time being whenever user does a payment I will take them out after the success and they can re-enter payment page again if they want to do another
